apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: elastiflow-logstash-oss
  name: elastiflow-logstash-oss
spec:
  containers:
  - env:
    - name: ELASTIFLOW_DEFAULT_APPID_SRCTYPE
      value: __UNKNOWN
    - name: ELASTIFLOW_IPFIX_TCP_IPV4_PORT
      value: "4739"
    - name: ELASTIFLOW_NAMESERVER
      value: 127.0.0.1
    - name: ELASTIFLOW_NETFLOW_IPV4_PORT
      value: "2055"
    - name: ELASTIFLOW_RESOLVE_IP2HOST
      value: "false"
    - name: ELASTIFLOW_SFLOW_IPV4_PORT
      value: "6343"
    - name: LS_JAVA_OPTS
      value: -Xms4g -Xmx4g
    - name: SERVER_HOST
      value: 0.0.0.0
    image: robcowart/elastiflow-logstash-oss:3.5.1
    name: elastiflow-logstash-oss
    resources: {}
  restartPolicy: Never
status: {}
