apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: elastiflow-elasticsearch-oss
  name: elastiflow-elasticsearch-oss
spec:
  containers:
  - env:
    - name: ES_JAVA_OPTS
      value: -Xms3g -Xmx3g
    - name: action.destructive_requires_name
      value: "true"
    - name: bootstrap.memory_lock
      value: "true"
    - name: cluster.name
      value: elastiflow
    - name: discovery.type
      value: single-node
    - name: http.port
      value: "9200"
    - name: indices.query.bool.max_clause_count
      value: "8192"
    - name: network.host
      value: 0.0.0.0
    - name: search.max_buckets
      value: "100000"
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.3.0
    name: elastiflow-elasticsearch-oss
    resources: {}
    volumeMounts:
    - mountPath: /usr/share/elasticsearch/data
      name: elastiflow-elasticsearch-oss-data
  restartPolicy: Never
  volumes:
  - name: elastiflow-elasticsearch-oss-data
    persistentVolumeClaim:
      claimName: elastiflow-elasticsearch-oss-data
status: {}
